### ISSUE TITLE
Progressbar option not working

### ISSUE THREAD

**Issue by hpurmann** [dergachev/screengif#15]
First of all: Thanks for the tool. I'm currently writing a blog post where I need a simple screencast gif.

I just wanted to try out the `progressbar` option but when executing, I get the following error:

```
$ screengif --progressbar --input screencast.mov --output screencast.gif
Processing image: 1/27/usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif/draw_progressbar.rb:29:in `draw': unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153: `(null)' (Magick::ImageMagickError)
        from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif/draw_progressbar.rb:29:in `draw'
        from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:98:in `block in start'
        from (eval):2:in `each'
        from (eval):2:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `each_with_index'
        from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/bin/screengif:10:in `<top (required)>'
        from /usr/local/bin/screengif:23:in `load'
        from /usr/local/bin/screengif:23:in `<main>'
```

Is there something missing in installation? Running on a MacOS 10.10.3 with up-to-date ffmpeg-2.6.3, imagemagick-6.9.1-4 and gifsicle-1.87.

**Comment by dergachev** [comment]
@hpurmann - thanks very much for trying out screengif.

Unfortunately I don't have enough hard drive space to install ffmpeg and friends on my laptop directly, so I can't easily test this issue. :(

I did just check it within the Docker, and everything works:
![demo2](https://cloud.githubusercontent.com/assets/135904/8185568/3cf9145c-1413-11e5-9250-9960af58ca62.gif)

I did Google the error message, and found a thread suggesting to run:

```
brew install gs
```

http://stackoverflow.com/questions/28043993/rmagick-unable-to-read-font

**Comment by hpurmann** [comment]
Thanks! Additional to `brew install gs` I needed to [install the fonts](http://sourceforge.net/projects/gs-fonts/?source=typ_redirect) on my system. Now it works. I've created a [PR](https://github.com/dergachev/screengif/pull/16) to include the section in the Readme.
