### ISSUE TITLE
Can I speed up a video?

### ISSUE THREAD

**Issue by fungku** [dergachev/screengif#17]
Say I have a 3 minute video and I want to have the gif be say, only 10 seconds -- can I do this with screengif script?

Just throw out a bunch of frames in between or something...

**Comment by dergachev** [comment]
I already support this. You need to play with a combination of these three args:

```
    -d, --delay MS                   Animation frame delay, in tens of ms. (default: 10)
        --delay-last MS              Animation frame delay of last frame, in tens of ms. (default: 50)
    -r, --framerate FPS              Specify amount of frames per second to keep. (default: 5)
```

**Comment by fungku** [comment]
Thanks, I was still having a hard time with large files.

I use screengif for short clips, and for large movie files I use this now:

```bash
# lgscreengif.sh
ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
cat $2 | convert -delay 5 - $2
```

**Comment by dergachev** [comment]
OK I'll keep this in mind, at some point in the future I should see what part of screengif fails for large fails. Thanks for offering this workaround, in the meantime!

**Comment by dergachev** [comment]
Oh, and for anyone curious about palette.png, see: http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html

**Comment by fungku** [comment]
My use case is probably pretty rare, my gifs are just me using the terminal for a project wiki, that will be seen by very few people. 

[Imgur](http://i.imgur.com/C4pqn6q.gifv)

However, some of them can get pretty long, and normally you don't want long gifs with a bunch of frames anyway.
