### ISSUE TITLE
What mouse pointer thing are you using in the gif?

### ISSUE THREAD

**Issue by pritianka** [dergachev/screengif#18]
Hi there!  I am excited to use screengif.  Quick question for you - what app/software are you using to get the black circle around your mouse? I'd like something like that for my screencasts.

**Comment by dergachev** [comment]
I believe it was just QuickTime which can record a screencast. Good luck!

On Saturday, 3 October 2015, Priyanka Sharma <notifications@github.com>
wrote:

> Hi there! I am excited to use screengif. Quick question for you - what
> app/software are you using to get the black circle around your mouse? I'd
> like something like that for my screencasts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dergachev/screengif/issues/18>.
>


-- 
------------------------------------------------------------------------------------
Alex Dergachev            Evolving Web
Lead developer            web design & development
alex@evolvingweb.ca        http://evolvingweb.ca
phone 514.844.4930        300 St Sacrement, #204
fax 514.807.7499        Montreal, QC, H2Y 1X4
------------------------------------------------------------------------------------

**Comment by pritianka** [comment]
So QuickTime let's you create the circle around the mouse pointer to
highlight it?  Thanks for your response!

Priyanka Sharma
Co-founder, WakaTime <http://www.wakatime.com/> - Quantify your coding
<http://www.twitter.com/pritianka>
www.twitter.com/pritianka
650-796-7125

**Comment by dergachev** [comment]
https://www.macstories.net/reviews/lions-quicktime-player-screen-recording-improvements-and-new-sharing-features/

On Saturday, 3 October 2015, Priyanka Sharma <notifications@github.com>
wrote:

> So QuickTime let's you create the circle around the mouse pointer to
> highlight it? Thanks for your response!
>
> Priyanka Sharma
> Co-founder, WakaTime <http://www.wakatime.com/> - Quantify your coding
> <http://www.twitter.com/pritianka>
> www.twitter.com/pritianka
> 650-796-7125
>
> On Fri, Oct 2, 2015 at 2:52 PM, Alex Dergachev <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I believe it was just QuickTime which can record a screencast. Good luck!
> >
> > On Saturday, 3 October 2015, Priyanka Sharma <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Hi there! I am excited to use screengif. Quick question for you - what
> > > app/software are you using to get the black circle around your mouse?
> I'd
> > > like something like that for my screencasts.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/dergachev/screengif/issues/18>.
> > >
> >
> >
> > --
> >
> >
> ------------------------------------------------------------------------------------
> > Alex Dergachev Evolving Web
> > Lead developer web design & development
> > alex@evolvingweb.ca
> <javascript:_e(%7B%7D,'cvml','alex@evolvingweb.ca');>
> http://evolvingweb.ca
> > phone 514.844.4930 300 St Sacrement, #204
> > fax 514.807.7499 Montreal, QC, H2Y 1X4
> >
> >
> ------------------------------------------------------------------------------------
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dergachev/screengif/issues/18#issuecomment-145164517
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dergachev/screengif/issues/18#issuecomment-145165726>.
>


-- 
------------------------------------------------------------------------------------
Alex Dergachev            Evolving Web
Lead developer            web design & development
alex@evolvingweb.ca        http://evolvingweb.ca
phone 514.844.4930        300 St Sacrement, #204
fax 514.807.7499        Montreal, QC, H2Y 1X4
------------------------------------------------------------------------------------
