### ISSUE TITLE
Using default options, resulting .gifs are faster than the .movs

### ISSUE THREAD

**Issue by IshmaelYavitz** [dergachev/screengif#24]
Whenever I convert a .mov using the default options - i.e. just

`screengif --input something.mov --output something.gif`

then the resulting .gif is faster than the .mov.  Not by a huge amount, but it's definitely noticeable.

**Comment by dergachev** [comment]
That's due to my personal preference, although on reflection I see how it might not be for everyone. I'd welcome a PR to include a note in the README about this. :)
