### ISSUE TITLE
`make build` errors with "error parsing `Gemfile`: There are no gemspecs at /tmp"

### ISSUE THREAD

**Issue by jasonferrier** [dergachev/screengif#25]
I have the latest from the repo and when I run `make build` (for the Docker option), it errors out. See message below.

Docker is running and no issues with that as I have other containers running with no problems.

**_------ CODE BLOCK BELOW (markdown won't respect my escaped backticks ``) ------_**

$ make build
Sending build context to Docker daemon 37.51 MB
Step 1 : FROM ubuntu:14.04
 ---> 6cc0fc2a5ee3
Step 2 : RUN route -n | awk '/^0.0.0.0/ {print $2}' > /tmp/host_ip.txt
 ---> Using cache
 ---> ef38b5b19185
Step 3 : RUN echo "HEAD /" | nc `cat /tmp/host_ip.txt` 8000 | grep squid-deb-proxy   && (echo "Acquire::http::Proxy \"http://$(cat /tmp/host_ip.txt):8000\";" > /etc/apt/apt.conf.d/30proxy)   && (echo "Acquire::http::Proxy::ppa.launchpad.net DIRECT;" >> /etc/apt/apt.conf.d/30proxy)   || echo "No squid-deb-proxy detected on docker host"
 ---> Using cache
 ---> 1cea9376280a
Step 4 : RUN apt-get update
 ---> Using cache
 ---> 192b1f4b1b0d
Step 5 : RUN apt-get install -y imagemagick
 ---> Using cache
 ---> 4b6e9eabc8cc
Step 6 : RUN apt-get install -y libmagickwand-dev
 ---> Using cache
 ---> 1e155565f867
Step 7 : RUN apt-get install -y gifsicle
 ---> Using cache
 ---> b2ecd7c40adb
Step 8 : RUN apt-get -y install ruby1.9.1 ruby1.9.1-dev
 ---> Using cache
 ---> dac138457075
Step 9 : RUN apt-get install -y build-essential curl git vim
 ---> Using cache
 ---> 1014eea43180
Step 10 : RUN apt-get install -y python-software-properties software-properties-common
 ---> Using cache
 ---> 7a6fe4cb8326
Step 11 : RUN add-apt-repository ppa:mc3man/trusty-media
 ---> Using cache
 ---> 50e9e22eef18
Step 12 : RUN apt-get update
 ---> Using cache
 ---> 57da197693e4
Step 13 : RUN apt-get -y install ffmpeg
 ---> Using cache
 ---> c2cc006e9cb2
Step 14 : RUN gem install bundler --no-rdoc --no-ri
 ---> Using cache
 ---> e220bf50751f
Step 15 : ADD Gemfile /tmp/Gemfile
 ---> Using cache
 ---> da6b3cb4d5f5
Step 16 : RUN cd /tmp; bundle install
 ---> Running in afd6fcb074cb
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

[!] There was an error parsing `Gemfile`: There are no gemspecs at /tmp. Bundler cannot continue.

 #  from /tmp/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #  -------------------------------------------
The command '/bin/sh -c cd /tmp; bundle install' returned a non-zero code: 15
make: *** [build] Error 1

**Comment by dergachev** [comment]
Strange, looks like you have an out-of-date Dockerfile!

Here's what it should look like:

```
RUN gem install bundler --no-rdoc --no-ri
ADD Gemfile screengif.gemspec /tmp/
RUN cd /tmp; bundle install
```

Run `git pull` and try again perhaps?
