### ISSUE TITLE
Extra installation instructions for Mac

### ISSUE THREAD

**Issue by richdougherty** [dergachev/screengif#27]
FYI I had to do a couple of extra things when installing on Mac 10.10.5 (Yosemite).

> `gem install screengif`

Before runnning this I needed to install `pkg-config`. Then, when I ran it, I needed `sudo`.

```
$ brew install pkg-config
$ sudo gem install screengif
```

**Comment by dergachev** [comment]
Thanks a ton, just updated the README!
