### ISSUE TITLE
command not found: screengif

### ISSUE THREAD

**Issue by azakordonets** [dergachev/screengif#28]
Hi, 

I've installed screengif gem : 
```
gem install screengif
Fetching: screengif-0.0.3.gem (100%)
Successfully installed screengif-0.0.3
Parsing documentation for screengif-0.0.3
Installing ri documentation for screengif-0.0.3
Done installing documentation for screengif after 0 seconds
1 gem installed
```

But when i try to execute command in terminal 
```
screengif -i Autocomplete_slowlyness.mov -o slow_autocomplete.gif
```

I get `command not found: screengif`

My ruby version is `ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]` and i'm on the latest Mac OSX version

**Comment by dergachev** [comment]
I guess you have a borked gem installation, maybe?
Or perhaps you installed it without sudo (not globally), but don't have the path setup?
Either figure out how to do that, or try `sudo gem install screengif`.

**Comment by azakordonets** [comment]
I did both sudo and no sudo - it was a same result

**Comment by azakordonets** [comment]
I did both sudo and no sudo - it was a same result

```
 ~  sudo gem install screengif
Fetching: screengif-0.0.3.gem (100%)
Successfully installed screengif-0.0.3
Parsing documentation for screengif-0.0.3
Installing ri documentation for screengif-0.0.3
Done installing documentation for screengif after 0 seconds
1 gem installed
➜  ~  gem install screengif
Fetching: screengif-0.0.3.gem (100%)
Successfully installed screengif-0.0.3
Parsing documentation for screengif-0.0.3
Installing ri documentation for screengif-0.0.3
Done installing documentation for screengif after 0 seconds
1 gem installed
```

**Comment by azakordonets** [comment]
Actually, it looks like i had to reload my zsh console to make it work. Weird, but good that it's working. Thanks for the script

**Comment by dergachev** [comment]
:+1:
