### ISSUE TITLE
Vagrant provisioner fails

### ISSUE THREAD

**Issue by LucianU** [dergachev/screengif#29]
I'm trying to use the Vagrantfile, but I get this error:
```
==> default: Gem::InstallError: rake requires Ruby version >= 1.9.3.
==> default: Using bundler 1.11.2
```

**Comment by dergachev** [comment]
Sorry, not enough info here. What commands did you run, exactly, starting from the `git clone`?
Perhaps also paste a gist of the entire log file.

**Comment by LucianU** [comment]
I had just ran git clone and vagrant up. Trying the second time worked though. Thank you for your time!

**Comment by dergachev** [comment]
👍
