### ISSUE TITLE
Install on OSX without homebrew

### ISSUE THREAD

**Issue by valeriyvan** [dergachev/screengif#33]
What's the way to install it on OSX without homebrew?
`make build` fails with:
docker build -t dergachev/screengif .
make: docker: No such file or directory
make: *** [build] Error 1

**Comment by jrunning** [comment]
I haven't tried it, but I suppose you would install the dependencies (XQuartz, ffmpeg ImageMagick, Gifsicle, and pkg-config) however you wish and then build and install the gem from source:

```sh
$ gem build screengif.gemspec
$ gem install screengif-<version>.gem
```

**Comment by dergachev** [comment]
If you look at the [Makefile](https://github.com/dergachev/screengif/blob/master/Makefile), you'll realize it's only useful for installing and running screengif in docker. To install screengif without homebrew, you'd find some other way to install it's dependencies (I haven't tried, on a mac). 

Then just run `gem install screengif` to install the gem as normal.
