### ISSUE TITLE
Wget command receiving 404 Not Found

### ISSUE THREAD

**Issue by rolyatwilson** [dergachev/screengif#35]
The wget command in the README is receiving a 404 Not Found:
`wget https://ghostscript.googlecode.com/files/ghostscript-fonts-std-8.11.tar.gz`

**Comment by dergachev** [comment]
Try `wget ftp://ftp.imagemagick.org/pub/ImageMagick/delegates/ghostscript-fonts-std-8.11.tar.gz` and see if everything works. If so, maybe make a PR :)

**Comment by dergachev** [comment]
Actually, it seems that now running `brew install gs` installs the fonts too: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghostscript.rb

Instead, don't download them separately and see if `--progressbar` just works. If so, let me know and I'll remove the unnecessary `wget` line from the README. :)
